name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger das Deployment, wenn auf den `main`-Branch gepusht wird

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Optional: Installiere Abhängigkeiten, falls du dies benötigst
    # - name: Install dependencies
    #   run: npm install

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Verwende das automatisch generierte GitHub Token
        publish_dir: ./dist  # Verzeichnis mit den fertigen Dateien (dist Ordner)
        # optional: commit_message: "Automated deployment"  # Falls du eine benutzerdefinierte Commit-Nachricht verwenden möchtest

